name: dkist

channels:
    - conda-forge

dependencies:
  - python=3.6
  - sphinx
  - dask
  - pip:
    - git+https://bitbucket.org/dkistdc/dkist-sphinx-theme.git
    - git+https://github.com/spacetelescope/asdf
    - git+https://github.com/spacetelescope/gwcs
    - git+https://github.com/sunpy/sunpy
    - ndcube
    - sphinx-astropy
