language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - SUNPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - EVENT_TYPE='pull_request push'
        
        # List other runtime dependencies for the package that are available as
        # conda packages here.
        - CONDA_DEPENDENCIES='asdf gwcs astropy sunpy ndcube pytest-astropy'
        
        # List other runtime dependencies for the package that are available as
        # pip packages here.
        - PIP_DEPENDENCIES=''

        - CONDA_CHANNELS='conda-forge'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # Do a PEP8 test with pycodestyle
        - os: linux
          env: MAIN_CMD='pycodestyle dkist --count' SETUP_CMD=''

install:

    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line below.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $SETUP_CMD == *coverage* ]]; then coveralls --rcfile='dkist/tests/coveragerc'; fi
