variables:
  Agent.Source.Git.ShallowFetchDepth: 1
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/sunpy/sunpy/_build/results?buildId=$(Build.BuildId)"

jobs:
  - template: azure-templates.yml
    parameters:
      name: Linux_36
      os: linux
      tox: py36 --
  
  - template: azure-templates.yml
    parameters:
      name: Linux_37
      os: linux
      tox: py37 --

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - template: azure-dkist-wheel.yaml
