variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/dkistdc/dkist/_build/results?buildId=$(Build.BuildId)"

jobs:
  # We are still running tests on Circle for now
  # - template: azure-templates.yml
  #   parameters:
  #     name: Linux_36
  #     os: linux
  #     tox: py36 --
  
  # - template: azure-templates.yml
  #   parameters:
  #     name: Linux_37
  #     os: linux
  #     tox: py37 --

  - template: azure-dkist-wheel.yaml
