name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  # These will need to be changed  for your project.
  CI_BUILD_URL: "https://dev.azure.com/sunpy/dkist/_build/results?buildId=$(Build.BuildId)"

# These resources need to be setup on the Azure Pipeline website
# as a service connection (if it has not been already).
resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: DKISTDC
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  tags:
    include:
    - 'v*'
    # exclude:
    # - '*dev*'
    # - '*pre*'
    # - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    coverage: codecov
    envs:
      - macos: py36
        name: macos_36

      - linux: py37
        name: linux_37

      - linux: py38
        name: linux_38

      - linux: codestyle


- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      dependsOn: [linux_37, linux_38, macos_36]
