jobs:
- job: Upload_dkist_wheel
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  pool:
    vmImage: Ubuntu 16.04

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: pip install --upgrade twine wheel setuptools_scm
    displayName: Install wheel requirements

  - task: TwineAuthenticate@0
    inputs:
      artifactFeeds: 'dkist_pypi'

  - script: >
      python -c "import setuptools_scm; print('##vso[task.setvariable variable=SETUPTOOLS_SCM_PRETEND_VERSION]' + setuptools_scm.get_version(local_scheme=lambda v: ''))"
    displayName: Remove local part from version

  - script: 'python setup.py sdist'
    displayName: Build sdist

  - script: 'python setup.py bdist_wheel --universal'
    displayName: Build Wheel

  - script: 'twine upload -r dkist_pypi --config-file $(PYPIRC_PATH) dist/*whl'
    displayName: Upload wheel
