deps-run: &cihelpers-install
  name: Install CI Helpers
  command: |
    git clone --depth 1 -b circleci git://github.com/cadair/ci-helpers.git
    source ci-helpers/travis/setup_dependencies_common.sh

version: 2
jobs:
  build:
    environment:
      - MINICONDA_BASE=/opt/conda
      - PYTHON_VERSION=3.6
      - SUNPY_VERSION=stable
      - MAIN_CMD=python setup.py
      - SETUP_CMD=test
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run: *cihelpers-install
      - run: $MAIN_CMD $SETUP_CMD
