apt-run: &apt-install
  name: Install apt packages
  command: |
    apt update
    apt install -y graphviz

deps-run: &cihelpers-install
  name: Install CI Helpers
  command: |
    git clone --depth 1 -b circleci git://github.com/cadair/ci-helpers.git
    source ci-helpers/travis/setup_dependencies_common.sh

build-run: &cihelpers-build
  name: Run Main Command
  command: |
    source activate test
    $MAIN_CMD $SETUP_CMD

version: 2
jobs:
  build:
    environment:
      - MPL_BACKEND: Agg
      - MINICONDA_BASE: "/opt/conda"
      - PYTHON_VERSION: "3.6"
      - CONDA_APPEND_CHANNELS: "conda-forge"
      - CONDA_DEPENDENCIES: "sphinx asdf gwcs sunpy"
      - MAIN_CMD: "python setup.py"
      - SETUP_CMD: "build_docs -W"
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run: *apt-install
      - run: *cihelpers-install
      - run: *cihelpers-build

      - store_artifacts:
          path: docs/_build/html

      - run:
          name: "Built documentation is available at:"
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/docs/_build/html/index.html"
