apt-run: &apt-install
  name: Install apt packages
  command: |
    apt update
    apt install -y graphviz texlive-latex-extra dvipng

deps-run: &cihelpers-install
  name: Install CI Helpers
  command: |
    git clone --depth 1 -b circleci git://github.com/cadair/ci-helpers.git
    source ci-helpers/travis/setup_dependencies_common.sh

build-run: &cihelpers-build
  name: Run Main Command
  command: |
    source activate test
    $MAIN_CMD $SETUP_CMD

version: 2
jobs:
  build:
    environment:
      - MINICONDA_BASE: "/opt/conda"
      - PYTHON_VERSION: "3.6"
      - CONDA_CHANNELS: "conda-forge"
      - CONDA_DEPENDENCIES: "sphinx"
      - SUNPY_VERSION: "stable"
      - MAIN_CMD: "python setup.py"
      - SETUP_CMD: "docs -W"
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run: *apt-install
      - run: *cihelpers-install
      - run: *cihelpers-build
