apt-run: &apt-install
  name: Install apt packages
  command: |
    apt update
    apt install -y graphviz npm

deps-run: &cihelpers-install
  name: Install CI Helpers
  command: |
    git clone --depth 1 -b circleci git://github.com/cadair/ci-helpers.git
    source ci-helpers/travis/setup_dependencies_common.sh

build-run: &cihelpers-build
  name: Run Main Command
  command: |
    source activate test
    $MAIN_CMD $SETUP_CMD

pip-run: &pip-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install -q --user $PIP_DEPENDENCIES
    pip install -q --user .

version: 2
jobs:
  build:
    environment:
      - PIP_DEPENDENCIES: "sphinx"
      - MAIN_CMD: "python setup.py"
      - SETUP_CMD: "build_docs -W"
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      # - run: *apt-install
      # - run: *cihelpers-install
      # - run: *cihelpers-build
      - run: *pip-install
      - run: $MAIN_CMD $SETUP_CMD

      - store_artifacts:
          path: docs/_build/html

      - run:
          name: "Built documentation is available at:"
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/docs/_build/html/index.html"
