apt-run: &apt-install
  name: Install apt packages
  command: |
    sudo apt update
    sudo apt install -y graphviz npm node

deps-run: &cihelpers-install
  name: Install CI Helpers
  command: |
    git clone --depth 1 -b circleci git://github.com/cadair/ci-helpers.git
    source ci-helpers/travis/setup_dependencies_common.sh

build-run: &cihelpers-build
  name: Run Main Command
  command: |
    source activate test
    $MAIN_CMD $SETUP_CMD

pip-run: &pip-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install --user $PIP_DEPENDENCIES

report-status: &report-status
  name: Report CI Status
  command: |
    npm install commit-status
    commit-status success docs "Your documentation built" $DOCS_URL

version: 2
jobs:
  build:
    environment:
      - PIP_DEPENDENCIES: "sphinx git+https://bitbucket.org/dkistdc/dkist-sphinx-theme.git sunpy asdf gwcs"
      - MAIN_CMD: "python setup.py"
      - SETUP_CMD: "build_docs -W"
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *apt-install
      - run: *pip-install
      - run: $MAIN_CMD $SETUP_CMD

      - store_artifacts:
          path: docs/_build/html

      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/docs/_build/html/index.html"; echo $DOCS_URL

      - run: *report-status
